version: '3'
services:
  # tf-serving:
  #   image: tensorflow/serving:latest
  #   restart: always
  #   ports:
  #     - '8501:8501'
  #   volumes:
  #     - './serving:/models'
  #     - './serving/models.conf:/models/models.conf'
  #   command:
  #     - '--model_config_file=/models/models.conf'
  #     - '--model_config_file_poll_wait_seconds=60'
  
  server:
    image: cristiando0902/tensorflow:1.14.0-py3
    restart: always
    volumes:
      - './:/env'
    command: bash /env/run.sh
    ports:
      - "5000:5000"
    networks:
      mynet:
        ipv4_address: 10.5.0.4

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1